# https://github.com/DanReker/CoAggregators

name: machine_learning
channels:
  - defaults
  - rdkit
  - anaconda
dependencies:
  - python=2.7
  - openpyxl=2.6.0
  - joblib=0.13.2
  - rdkit=2018.09.3.0
  - scikit-learn=0.20.3
